name: Build domains
on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"
      timezone: "Asia/Shanghai"
  push:
    branches:
      - main
    paths-ignore:
      - "**/README.md"

permissions:
  contents: write
  actions: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set variables
        run: |
          echo "update_version=$(date -d '+8 hours' +%Y-%m-%d)" >> "${GITHUB_ENV}"
          echo "fakeip_filter=https://raw.githubusercontent.com/DustinWin/ShellCrash/dev/public/fake_ip_filter.list" >> "${GITHUB_ENV}"
          echo "ads=https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-clash.yaml" >> "${GITHUB_ENV}"
          echo "private=https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Lan/Lan.list" >> "${GITHUB_ENV}"
          echo "trackerslist1=https://raw.githubusercontent.com/XIU2/TrackersListCollection/master/all.txt" >> "${GITHUB_ENV}"
          echo "trackerslist2=https://raw.githubusercontent.com/ngosang/trackerslist/master/trackers_all.txt" >> "${GITHUB_ENV}"
          echo "applications1=https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Download/Download.list" >> "${GITHUB_ENV}"
          echo "applications2=https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/applications.txt" >> "${GITHUB_ENV}"
          echo "apple_cn=https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/apple.china.conf" >> "${GITHUB_ENV}"
          echo "google_cn1=https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/google.china.conf" >> "${GITHUB_ENV}"
          echo "google_cn2=https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GoogleFCM/GoogleFCM.list" >> "${GITHUB_ENV}"
          echo "games_cn1=https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Game/GameDownloadCN/GameDownloadCN.list" >> "${GITHUB_ENV}"
          echo "games_cn2=https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/SteamCN/SteamCN.list" >> "${GITHUB_ENV}"
          echo "games1=https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Game/Game.list" >> "${GITHUB_ENV}"
          echo "games2=https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Game/GameDownload/GameDownload.list" >> "${GITHUB_ENV}"
          echo "netflix=https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Netflix/Netflix.list" >> "${GITHUB_ENV}"
          echo "disney=https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Disney/Disney.list" >> "${GITHUB_ENV}"
          echo "max=https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/HBO/HBO.list" >> "${GITHUB_ENV}"
          echo "primevideo=https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/PrimeVideo/PrimeVideo.list" >> "${GITHUB_ENV}"
          echo "appletv=https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/AppleTV/AppleTV.list" >> "${GITHUB_ENV}"
          echo "youtube=https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/YouTube/YouTube.list" >> "${GITHUB_ENV}"
          echo "tiktok=https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/TikTok/TikTok.list" >> "${GITHUB_ENV}"
          echo "bilibili=https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/BiliBili/BiliBili.list" >> "${GITHUB_ENV}"
          echo "spotify=https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Spotify/Spotify.list" >> "${GITHUB_ENV}"
          echo "media=https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GlobalMedia/GlobalMedia.list" >> "${GITHUB_ENV}"
          echo "ai=https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/AI.list" >> "${GITHUB_ENV}"
          echo "networktest=https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Speedtest/Speedtest.list" >> "${GITHUB_ENV}"
          echo "cn1=https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/accelerated-domains.china.conf" >> "${GITHUB_ENV}"
          echo "cn2=https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/China/China.list" >> "${GITHUB_ENV}"
        shell: bash

      - name: Checkout codebase
        uses: actions/checkout@v7

      - name: Setup Go
        uses: actions/setup-go@v7
        with:
          go-version-file: ./go.mod

      - name: Checkout `v2fly/domain-list-community`
        uses: actions/checkout@v7
        with:
          repository: v2fly/domain-list-community
          path: community

      - name: Checkout `cokebar/gfwlist2dnsmasq`
        uses: actions/checkout@v7
        with:
          repository: cokebar/gfwlist2dnsmasq
          path: gfwlist2dnsmasq

      - name: Generate `mihomo` geosite.dat and domains (.txt files)
        run: |
          go run ./ --datapath=./community/data/

      - name: Ready for remove redundant rules (`games-cn`, `games`, `media`, `ai`, `proxy`, `cn`, `cn-lite`)
        run: |
          mkdir -p ./tmp/ ./domains/
          chmod +x ./tools/*.py ./tools/filter.sh

          # suffix for `games-cn`
          cat ./publish/category-enhance-gaming.txt | perl -ne '/^(domain):([^:]+):\@cn$/ && print "$2\n"' > ./tmp/temp-games-cn-unsort-suffix.txt
          cat ./publish/category-game-accelerator-cn.txt | perl -ne '/^(domain):([^:]+)(\n$|:\@.+)/ && print "$2\n"' >> ./tmp/temp-games-cn-unsort-suffix.txt
          cat ./publish/category-game-platforms-download.txt | perl -ne '/^(domain):([^:]+):\@cn$/ && print "$2\n"' >> ./tmp/temp-games-cn-unsort-suffix.txt
          cat ./publish/category-games-cn.txt | perl -ne '/^(domain):([^:]+)(\n$|:\@.+)/ && print "$2\n"' >> ./tmp/temp-games-cn-unsort-suffix.txt
          curl -fsSL "${games_cn1}" | awk '/DOMAIN-SUFFIX,/' | sed 's/DOMAIN-SUFFIX,//' >> ./tmp/temp-games-cn-unsort-suffix.txt
          curl -fsSL "${games_cn2}" | awk '/DOMAIN-SUFFIX,/' | sed 's/DOMAIN-SUFFIX,//' >> ./tmp/temp-games-cn-unsort-suffix.txt
          sort --ignore-case -u ./tmp/temp-games-cn-unsort-suffix.txt > ./tmp/temp-games-cn-sort-suffix.txt

          # domain for `games-cn`
          cat ./publish/category-enhance-gaming.txt | perl -ne '/^(full):([^:]+):\@cn$/ && print "$2\n"' > ./tmp/temp-games-cn-unsort-domain.txt
          cat ./publish/category-game-accelerator-cn.txt | perl -ne '/^(full):([^:]+)(\n$|:\@.+)/ && print "$2\n"' >> ./tmp/temp-games-cn-unsort-domain.txt
          cat ./publish/category-game-platforms-download.txt | perl -ne '/^(full):([^:]+):\@cn$/ && print "$2\n"' >> ./tmp/temp-games-cn-unsort-domain.txt
          cat ./publish/category-games-cn.txt | perl -ne '/^(full):([^:]+)(\n$|:\@.+)/ && print "$2\n"' >> ./tmp/temp-games-cn-unsort-domain.txt
          curl -fsSL "${games_cn1}" | awk '/DOMAIN,/' | sed 's/DOMAIN,//' >> ./tmp/temp-games-cn-unsort-domain.txt
          curl -fsSL "${games_cn2}" | awk '/DOMAIN,/' | sed 's/DOMAIN,//' >> ./tmp/temp-games-cn-unsort-domain.txt
          sort --ignore-case -u ./tmp/temp-games-cn-unsort-domain.txt > ./tmp/temp-games-cn-sort-domain.txt

          # keyword for `games-cn`
          cat ./publish/category-enhance-gaming.txt | perl -ne '/^(keyword):([^:]+):\@cn$/ && print "$2\n"' > ./tmp/temp-games-cn-unsort-keyword.txt
          cat ./publish/category-game-accelerator-cn.txt | perl -ne '/^(keyword):([^:]+)(\n$|:\@.+)/ && print "$2\n"' >> ./tmp/temp-games-cn-unsort-keyword.txt
          cat ./publish/category-game-platforms-download.txt | perl -ne '/^(keyword):([^:]+):\@cn$/ && print "$2\n"' >> ./tmp/temp-games-cn-unsort-keyword.txt
          cat ./publish/category-games-cn.txt | perl -ne '/^(keyword):([^:]+)(\n$|:\@.+)/ && print "$2\n"' >> ./tmp/temp-games-cn-unsort-keyword.txt
          curl -fsSL "${games_cn1}" | awk '/DOMAIN-KEYWORD,/' | sed 's/DOMAIN-KEYWORD,//' >> ./tmp/temp-games-cn-unsort-keyword.txt
          curl -fsSL "${games_cn2}" | awk '/DOMAIN-KEYWORD,/' | sed 's/DOMAIN-KEYWORD,//' >> ./tmp/temp-games-cn-unsort-keyword.txt
          sort --ignore-case -u ./tmp/temp-games-cn-unsort-keyword.txt > ./tmp/temp-games-cn-sort-keyword.txt

          # suffix for `games`
          cat ./publish/category-enhance-gaming.txt | perl -ne '/^(domain):([^:]+)(\n$|:\@!cn$)/ && print "$2\n"' > ./tmp/temp-games-unsort-suffix.txt
          cat ./publish/category-game-platforms-download.txt | perl -ne '/^(domain):([^:]+)(\n$|:\@!cn$)/ && print "$2\n"' >> ./tmp/temp-games-unsort-suffix.txt
          cat ./publish/category-games-\!cn.txt | perl -ne '/^(domain):([^:]+)(\n$|:\@.+)/ && print "$2\n"' >> ./tmp/temp-games-unsort-suffix.txt
          curl -fsSL "${games1}" | awk '/DOMAIN-SUFFIX,/' | sed 's/DOMAIN-SUFFIX,//' >> ./tmp/temp-games-unsort-suffix.txt
          curl -fsSL "${games2}" | awk '/DOMAIN-SUFFIX,/' | sed 's/DOMAIN-SUFFIX,//' >> ./tmp/temp-games-unsort-suffix.txt
          sort --ignore-case -u ./tmp/temp-games-unsort-suffix.txt > ./tmp/temp-games-sort-suffix.txt

          # domain for `games`
          cat ./publish/category-enhance-gaming.txt | perl -ne '/^(full):([^:]+)(\n$|:\@!cn$)/ && print "$2\n"' > ./tmp/temp-games-unsort-domain.txt
          cat ./publish/category-game-platforms-download.txt | perl -ne '/^(full):([^:]+)(\n$|:\@!cn$)/ && print "$2\n"' >> ./tmp/temp-games-unsort-domain.txt
          cat ./publish/category-games-\!cn.txt | perl -ne '/^(full):([^:]+)(\n$|:\@.+)/ && print "$2\n"' >> ./tmp/temp-games-unsort-domain.txt
          curl -fsSL "${games1}" | awk '/DOMAIN,/' | sed 's/DOMAIN,//' >> ./tmp/temp-games-unsort-domain.txt
          curl -fsSL "${games2}" | awk '/DOMAIN,/' | sed 's/DOMAIN,//' >> ./tmp/temp-games-unsort-domain.txt
          sort --ignore-case -u ./tmp/temp-games-unsort-domain.txt > ./tmp/temp-games-sort-domain.txt

          # keyword for `games`
          cat ./publish/category-enhance-gaming.txt | perl -ne '/^(keyword):([^:]+)(\n$|:\@!cn$)/ && print "$2\n"' > ./tmp/temp-games-unsort-keyword.txt
          cat ./publish/category-game-platforms-download.txt | perl -ne '/^(keyword):([^:]+)(\n$|:\@!cn$)/ && print "$2\n"' >> ./tmp/temp-games-unsort-keyword.txt
          cat ./publish/category-games-\!cn.txt | perl -ne '/^(keyword):([^:]+)(\n$|:\@.+)/ && print "$2\n"' >> ./tmp/temp-games-unsort-keyword.txt
          curl -fsSL "${games1}" | awk '/DOMAIN-KEYWORD,/' | sed 's/DOMAIN-KEYWORD,//' >> ./tmp/temp-games-unsort-keyword.txt
          curl -fsSL "${games2}" | awk '/DOMAIN-KEYWORD,/' | sed 's/DOMAIN-KEYWORD,//' >> ./tmp/temp-games-unsort-keyword.txt
          sort --ignore-case -u ./tmp/temp-games-unsort-keyword.txt > ./tmp/temp-games-sort-keyword.txt

          # suffix for `media`
          curl -fsSL "${media}" | awk '/DOMAIN-SUFFIX,/' | sed 's/DOMAIN-SUFFIX,//' | sort --ignore-case > ./tmp/temp-media-sort-suffix.txt

          # domain for `media`
          curl -fsSL "${media}" | awk '/DOMAIN,/' | sed 's/DOMAIN,//' | sort --ignore-case > ./tmp/temp-media-sort-domain.txt

          # keyword for `media`
          curl -fsSL "${media}" | awk '/DOMAIN-KEYWORD,/' | sed 's/DOMAIN-KEYWORD,//' | sort --ignore-case > ./tmp/temp-media-sort-keyword.txt

          # suffix for `ai`
          cat ./publish/category-ai-\!cn.txt | perl -ne '/^(domain):([^:]+)(\n$|:\@.+)/ && print "$2\n"' > ./tmp/temp-ai-unsort-suffix.txt
          curl -fsSL "${ai}" | awk '/DOMAIN-SUFFIX,/' | sed 's/DOMAIN-SUFFIX,//' >> ./tmp/temp-ai-unsort-suffix.txt
          sort --ignore-case -u ./tmp/temp-ai-unsort-suffix.txt > ./tmp/temp-ai-sort-suffix.txt

          # domain for `ai`
          cat ./publish/category-ai-\!cn.txt | perl -ne '/^(full):([^:]+)(\n$|:\@.+)/ && print "$2\n"' > ./tmp/temp-ai-unsort-domain.txt
          curl -fsSL "${ai}" | awk '/DOMAIN,/' | sed 's/DOMAIN,//' >> ./tmp/temp-ai-unsort-domain.txt
          sort --ignore-case -u ./tmp/temp-ai-unsort-domain.txt > ./tmp/temp-ai-sort-domain.txt

          # keyword for `ai`
          cat ./publish/category-ai-\!cn.txt | perl -ne '/^(keyword):([^:]+)(\n$|:\@.+)/ && print "$2\n"' > ./tmp/temp-ai-unsort-keyword.txt
          curl -fsSL "${ai}" | awk '/DOMAIN-KEYWORD,/' | sed 's/DOMAIN-KEYWORD,//' >> ./tmp/temp-ai-unsort-keyword.txt
          sort --ignore-case -u ./tmp/temp-ai-unsort-keyword.txt > ./tmp/temp-ai-sort-keyword.txt

          # suffix for `proxy`
          chmod +x ./gfwlist2dnsmasq/gfwlist2dnsmasq.sh
          ./gfwlist2dnsmasq/gfwlist2dnsmasq.sh -l -o ./tmp/temp-gfw.txt
          cat ./tmp/temp-gfw.txt | perl -ne '/^((?=^.{3,255})[a-zA-Z0-9][-_a-zA-Z0-9]{0,62}(\.[a-zA-Z0-9][-_a-zA-Z0-9]{0,62})+)/ && print "$1\n"' > ./tmp/temp-proxy-unsort-suffix.txt
          cat ./publish/geolocation-\!cn.txt | perl -ne '/^(domain):([^:]+)(\n$|:\@.+)/ && print "$2\n"' >> ./tmp/temp-proxy-unsort-suffix.txt
          sort --ignore-case -u ./tmp/temp-proxy-unsort-suffix.txt > ./tmp/temp-proxy-sort-suffix.txt

          # domain for `proxy`
          cat ./publish/geolocation-\!cn.txt | perl -ne '/^(full):([^:]+)(\n$|:\@.+)/ && print "$2\n"' | sort --ignore-case > ./tmp/temp-proxy-sort-domain.txt

          # keyword for `proxy`
          cat ./publish/geolocation-\!cn.txt | perl -ne '/^(keyword):([^:]+)(\n$|:\@.+)/ && print "$2\n"' | sort --ignore-case > ./tmp/temp-proxy-sort-keyword.txt

          # suffix for `cn`
          cat ./publish/cn.txt | perl -ne '/^(domain):([^:]+)(\n$|:\@.+)/ && print "$2\n"' > ./tmp/temp-cn-unsort-suffix.txt
          curl -fsSL "${cn1}" | awk '!/# Disabled/' | perl -ne '/server=\/([^\/]+)/ && print "$1\n"' >> ./tmp/temp-cn-unsort-suffix.txt
          sort --ignore-case -u ./tmp/temp-cn-unsort-suffix.txt > ./tmp/temp-cn-sort-suffix.txt

          # domain for `cn`
          cat ./publish/cn.txt | perl -ne '/^(full):([^:]+)(\n$|:\@.+)/ && print "$2\n"' | sort --ignore-case > ./tmp/temp-cn-sort-domain.txt

          # keyword for `cn`
          cat ./publish/cn.txt | perl -ne '/^(keyword):([^:]+)(\n$|:\@.+)/ && print "$2\n"' | sort --ignore-case > ./tmp/temp-cn-sort-keyword.txt

          # suffix for `cn-lite`
          cat ./publish/cn.txt | perl -ne '/^(domain):([^:]+)(\n$|:\@.+)/ && print "$2\n"' > ./tmp/temp-cn-lite-unsort-suffix.txt
          curl -fsSL "${cn2}" | awk '/DOMAIN-SUFFIX,/' | sed 's/DOMAIN-SUFFIX,//' >> ./tmp/temp-cn-lite-unsort-suffix.txt
          sort --ignore-case -u ./tmp/temp-cn-lite-unsort-suffix.txt > ./tmp/temp-cn-lite-sort-suffix.txt

          # domain for `cn-lite`
          cat ./publish/cn.txt | perl -ne '/^(full):([^:]+)(\n$|:\@.+)/ && print "$2\n"' > ./tmp/temp-cn-lite-unsort-domain.txt
          curl -fsSL "${cn2}" | awk '/DOMAIN,/' | sed 's/DOMAIN,//' >> ./tmp/temp-cn-lite-unsort-domain.txt
          sort --ignore-case -u ./tmp/temp-cn-lite-unsort-domain.txt > ./tmp/temp-cn-lite-sort-domain.txt

          # keyword for `cn-lite`
          cat ./publish/cn.txt | perl -ne '/^(keyword):([^:]+)(\n$|:\@.+)/ && print "$2\n"' > ./tmp/temp-cn-lite-unsort-keyword.txt
          curl -fsSL "${cn2}" | awk '/DOMAIN-KEYWORD,/' | sed 's/DOMAIN-KEYWORD,//' >> ./tmp/temp-cn-lite-unsort-keyword.txt
          sort --ignore-case -u ./tmp/temp-cn-lite-unsort-keyword.txt > ./tmp/temp-cn-lite-sort-keyword.txt

      - name: Generate `fakeip-filter`
        run: |
          cat ./publish/category-ntp.txt | perl -ne '/^(domain):([^:]+)(\n$|:\@.+)/ && print "$2\n"' > ./tmp/temp-fakeip-filter-suffix.txt
          cat ./publish/category-stun.txt | perl -ne '/^(domain):([^:]+)(\n$|:\@.+)/ && print "$2\n"' >> ./tmp/temp-fakeip-filter-suffix.txt
          curl -fsSL "${fakeip_filter}" | perl -ne '/^[\+\*]\.([^\*]+)\n$/ && print "$1\n"' >> ./tmp/temp-fakeip-filter-suffix.txt
          sort --ignore-case -u ./tmp/temp-fakeip-filter-suffix.txt > ./tmp/fakeip-filter-suffix.txt

          cat ./publish/category-ntp.txt | perl -ne '/^(full):([^:]+)(\n$|:\@.+)/ && print "DOMAIN,$2\n"' > ./tmp/temp-fakeip-filter-other.txt
          cat ./publish/category-stun.txt | perl -ne '/^(full):([^:]+)(\n$|:\@.+)/ && print "DOMAIN,$2\n"' >> ./tmp/temp-fakeip-filter-other.txt
          curl -fsSL "${fakeip_filter}" | awk '!/[#+* ]|ntp|stun|time/' | sed 's/^/DOMAIN,/' >> ./tmp/temp-fakeip-filter-other.txt
          sort --ignore-case -u ./tmp/temp-fakeip-filter-other.txt > ./tmp/fakeip-filter-other.txt

      - name: Generate `fakeip-filter-lite`
        run: |
          cat ./publish/category-ntp.txt | perl -ne '/^(domain):([^:]+)(\n$|:\@.+)/ && print "$2\n"' > ./tmp/temp-fakeip-filter-lite-suffix.txt
          cat ./publish/category-stun.txt | perl -ne '/^(domain):([^:]+)(\n$|:\@.+)/ && print "$2\n"' >> ./tmp/temp-fakeip-filter-lite-suffix.txt
          sort --ignore-case -u ./tmp/temp-fakeip-filter-lite-suffix.txt > ./tmp/fakeip-filter-lite-suffix.txt

          cat <<EOF > ./tmp/temp-fakeip-filter-lite-other.txt
          DOMAIN,adguardteam.github.io
          DOMAIN,adrules.top
          DOMAIN,anti-ad.net
          DOMAIN,local.adguard.org
          DOMAIN,static.adtidy.org
          EOF
          cat ./publish/category-ntp.txt | perl -ne '/^(full):([^:]+)(\n$|:\@.+)/ && print "DOMAIN,$2\n"' >> ./tmp/temp-fakeip-filter-lite-other.txt
          cat ./publish/category-stun.txt | perl -ne '/^(full):([^:]+)(\n$|:\@.+)/ && print "DOMAIN,$2\n"' >> ./tmp/temp-fakeip-filter-lite-other.txt
          sort --ignore-case -u ./tmp/temp-fakeip-filter-lite-other.txt > ./tmp/fakeip-filter-lite-other.txt

      - name: Generate `ads`
        run: |
          curl -fsSL "${ads}" | perl -ne "/'([^']+)'/ && print \"\$1\n\"" | sed 's/^+\./DOMAIN-SUFFIX,/; t; s/^/DOMAIN,/' | sort --ignore-case > ./domains/ads.list

      - name: Generate `private`
        run: |
          cat ./publish/private.txt | perl -ne '/^(domain):([^:]+)(\n$|:\@.+)/ && print "$2\n"' > ./tmp/temp-private-suffix.txt
          curl -fsSL "${private}" | awk '/DOMAIN-SUFFIX,/' | sed 's/DOMAIN-SUFFIX,//' >> ./tmp/temp-private-suffix.txt
          sort --ignore-case -u ./tmp/temp-private-suffix.txt > ./tmp/private-suffix.txt

          cat <<EOF > ./tmp/temp-private-other.txt
          DOMAIN,board.zash.run.place
          DOMAIN,zephyruso.github.io
          DOMAIN,dash.sing-box.app
          DOMAIN,metacubex.github.io
          DOMAIN,metacubexd.pages.dev
          DOMAIN,sing-box-dashboard.sagernet.org
          DOMAIN,yacd.metacubex.one
          EOF
          cat ./publish/private.txt | perl -ne '/^(full):([^:]+)(\n$|:\@.+)/ && print "DOMAIN,$2\n"' >> ./tmp/temp-private-other.txt
          cat ./publish/private.txt | perl -ne '/^(keyword):([^:]+)(\n$|:\@.+)/ && print "DOMAIN-KEYWORD,$2\n"' >> ./tmp/temp-private-other.txt
          curl -fsSL "${private}" | awk '/(DOMAIN,|DOMAIN-KEYWORD,)/' >> ./tmp/temp-private-other.txt
          sort --ignore-case -u ./tmp/temp-private-other.txt > ./tmp/private-other.txt

      - name: Generate `trackerslist`
        run: |
          curl -fsSL "${trackerslist1}" | grep -i '\.[A-Z]' | awk -F '[/:]' '{print $4}' | sed 's/^/DOMAIN,/' > ./tmp/temp-trackerslist.txt
          curl -fsSL "${trackerslist2}" | grep -i '\.[A-Z]' | awk -F '[/:]' '{print $4}' | sed 's/^/DOMAIN,/' >> ./tmp/temp-trackerslist.txt
          sort --ignore-case -u ./tmp/temp-trackerslist.txt > ./domains/trackerslist.list

      - name: Generate `applications`
        run: |
          curl -fsSL "${applications1}" | awk '/(DOMAIN,|DOMAIN-SUFFIX,|DOMAIN-KEYWORD,|PROCESS-NAME,)/' > ./tmp/temp-applications.txt
          curl -fsSL "${applications2}" | perl -ne '/^\s*-\s+(.*)/ && print "$1\n"' >> ./tmp/temp-applications.txt
          sort --ignore-case -u ./tmp/temp-applications.txt > ./domains/applications.list

      - name: Generate `microsoft-cn`
        run: |
          cat ./publish/microsoft.txt | perl -ne '/^(domain):([^:]+):\@cn$/ && print "$2\n"' | sort --ignore-case > ./tmp/microsoft-cn-suffix.txt

          cat ./publish/microsoft.txt | perl -ne '/^(full):([^:]+):\@cn$/ && print "DOMAIN,$2\n"' > ./tmp/temp-microsoft-cn-other.txt
          cat ./publish/microsoft.txt | perl -ne '/^(keyword):([^:]+):\@cn$/ && print "DOMAIN-KEYWORD,$2\n"' >> ./tmp/temp-microsoft-cn-other.txt
          sort --ignore-case ./tmp/temp-microsoft-cn-other.txt > ./tmp/microsoft-cn-other.txt

      - name: Generate `apple-cn`
        run: |
          cat ./publish/apple.txt | perl -ne '/^(domain):([^:]+):\@cn$/ && print "$2\n"' > ./tmp/temp-apple-cn-suffix.txt
          curl -fsSL "${apple_cn}" | awk '!/# Disabled/' | perl -ne '/server=\/([^\/]+)/ && print "$1\n"' >> ./tmp/temp-apple-cn-suffix.txt
          sort --ignore-case -u ./tmp/temp-apple-cn-suffix.txt > ./tmp/apple-cn-suffix.txt

          cat ./publish/apple.txt | perl -ne '/^(full):([^:]+):\@cn$/ && print "DOMAIN,$2\n"' > ./tmp/temp-apple-cn-other.txt
          cat ./publish/apple.txt | perl -ne '/^(keyword):([^:]+):\@cn$/ && print "DOMAIN-KEYWORD,$2\n"' >> ./tmp/temp-apple-cn-other.txt
          sort --ignore-case ./tmp/temp-apple-cn-other.txt > ./tmp/apple-cn-other.txt

      - name: Generate `google-cn`
        run: |
          cat ./publish/google.txt | perl -ne '/^(domain):([^:]+):\@cn$/ && print "$2\n"' > ./tmp/temp-google-cn-suffix.txt
          curl -fsSL "${google_cn1}" | awk '!/# Disabled/' | perl -ne '/server=\/([^\/]+)/ && print "$1\n"' >> ./tmp/temp-google-cn-suffix.txt
          curl -fsSL "${google_cn2}" | awk '/DOMAIN-SUFFIX,/' | sed 's/DOMAIN-SUFFIX,//' >> ./tmp/temp-google-cn-suffix.txt
          sort --ignore-case -u ./tmp/temp-google-cn-suffix.txt > ./tmp/google-cn-suffix.txt

          cat ./publish/google.txt | perl -ne '/^(full):([^:]+):\@cn$/ && print "DOMAIN,$2\n"' > ./tmp/temp-google-cn-other.txt
          cat ./publish/google.txt | perl -ne '/^(keyword):([^:]+):\@cn$/ && print "DOMAIN-KEYWORD,$2\n"' >> ./tmp/temp-google-cn-other.txt
          curl -fsSL "${google_cn2}" | awk '/(DOMAIN,|DOMAIN-KEYWORD,)/' >> ./tmp/temp-google-cn-other.txt
          sort --ignore-case -u ./tmp/temp-google-cn-other.txt > ./tmp/google-cn-other.txt

      - name: Generate `games-cn`
        run: |
          cp -f ./tmp/temp-games-cn-sort-suffix.txt ./tmp/games-cn-suffix.txt

          cat ./tmp/temp-games-cn-sort-domain.txt | sed 's/^/DOMAIN,/' > ./tmp/temp-games-cn-other.txt
          cat ./tmp/temp-games-cn-sort-keyword.txt | sed 's/^/DOMAIN-KEYWORD,/' >> ./tmp/temp-games-cn-other.txt
          cat ./tmp/temp-games-cn-other.txt | sort --ignore-case > ./tmp/games-cn-other.txt

      - name: Generate `games`
        run: |
          # Remove `games-cn` from `games` (suffix)
          python ./tools/removeFrom.py -remove ./tmp/temp-games-cn-sort-suffix.txt -from ./tmp/temp-games-sort-suffix.txt -out ./tmp/temp-games-without-cn-suffix.txt
          python ./tools/removeFrom.py -remove ./tmp/temp-games-cn-sort-domain.txt -from ./tmp/temp-games-without-cn-suffix.txt -out ./tmp/temp-games-without-cn-done-suffix.txt
          cat ./tmp/temp-games-without-cn-done-suffix.txt | sort --ignore-case > ./tmp/games-suffix.txt

          # Remove `games-cn` from `games` (domain)
          python ./tools/removeFrom.py -remove ./tmp/temp-games-cn-sort-suffix.txt -from ./tmp/temp-games-sort-domain.txt -out ./tmp/temp-games-without-cn-domain.txt
          python ./tools/removeFrom.py -remove ./tmp/temp-games-cn-sort-domain.txt -from ./tmp/temp-games-without-cn-domain.txt -out ./tmp/temp-games-without-cn-done-domain.txt
          cat ./tmp/temp-games-without-cn-done-domain.txt | sed 's/^/DOMAIN,/' | sort --ignore-case > ./tmp/temp-games-without-cn-filter-domain.txt
          cat ./tmp/temp-games-cn-sort-suffix.txt | sed 's/^/DOMAIN-SUFFIX,/' | sort --ignore-case > ./tmp/temp-games-cn-filter-suffix.txt
          cat ./tmp/temp-games-without-cn-filter-domain.txt ./tmp/temp-games-cn-filter-suffix.txt > ./tmp/temp-games-redundant.txt
          ./tools/filter.sh ./tmp/temp-games-redundant.txt > ./tmp/temp-games-done.txt
          cat ./tmp/temp-games-done.txt | awk '/DOMAIN,/' > ./tmp/temp-games-domain.txt

          # Remove `games-cn` from `games` (keyword)
          python ./tools/removeFrom.py -remove ./tmp/temp-games-cn-sort-keyword.txt -from ./tmp/temp-games-sort-keyword.txt -out ./tmp/temp-games-without-cn-done-keyword.txt
          cat ./tmp/temp-games-without-cn-done-keyword.txt | sed 's/^/DOMAIN-KEYWORD,/' | sort --ignore-case > ./tmp/temp-games-keyword.txt

          # Merge rules for `games`
          cat ./tmp/temp-games-domain.txt ./tmp/temp-games-keyword.txt > ./tmp/games-other.txt

      - name: Generate `netflix`
        run: |
          cat ./publish/netflix.txt | perl -ne '/^(domain):([^:]+)(\n$|:\@.+)/ && print "$2\n"' > ./tmp/temp-netflix-suffix.txt
          curl -fsSL "${netflix}" | awk '/DOMAIN-SUFFIX,/' | sed 's/DOMAIN-SUFFIX,//' >> ./tmp/temp-netflix-suffix.txt
          sort --ignore-case -u ./tmp/temp-netflix-suffix.txt > ./tmp/netflix-suffix.txt

          cat ./publish/netflix.txt | perl -ne '/^(full):([^:]+)(\n$|:\@.+)/ && print "DOMAIN,$2\n"' > ./tmp/temp-netflix-other.txt
          cat ./publish/netflix.txt | perl -ne '/^(keyword):([^:]+)(\n$|:\@.+)/ && print "DOMAIN-KEYWORD,$2\n"' >> ./tmp/temp-netflix-other.txt
          curl -fsSL "${netflix}" | awk '/(DOMAIN,|DOMAIN-KEYWORD,)/' >> ./tmp/temp-netflix-other.txt
          sort --ignore-case -u ./tmp/temp-netflix-other.txt > ./tmp/netflix-other.txt

      - name: Generate `disney`
        run: |
          cat ./publish/disney.txt | perl -ne '/^(domain):([^:]+)(\n$|:\@.+)/ && print "$2\n"' > ./tmp/temp-disney-suffix.txt
          curl -fsSL "${disney}" | awk '/DOMAIN-SUFFIX,/' | sed 's/DOMAIN-SUFFIX,//' >> ./tmp/temp-disney-suffix.txt
          sort --ignore-case -u ./tmp/temp-disney-suffix.txt > ./tmp/disney-suffix.txt

          cat ./publish/disney.txt | perl -ne '/^(full):([^:]+)(\n$|:\@.+)/ && print "DOMAIN,$2\n"' > ./tmp/temp-disney-other.txt
          cat ./publish/disney.txt | perl -ne '/^(keyword):([^:]+)(\n$|:\@.+)/ && print "DOMAIN-KEYWORD,$2\n"' >> ./tmp/temp-disney-other.txt
          curl -fsSL "${disney}" | awk '/(DOMAIN,|DOMAIN-KEYWORD,)/' >> ./tmp/temp-disney-other.txt
          sort --ignore-case -u ./tmp/temp-disney-other.txt > ./tmp/disney-other.txt

      - name: Generate `max`
        run: |
          cat ./publish/hbo.txt | perl -ne '/^(domain):([^:]+)(\n$|:\@.+)/ && print "$2\n"' > ./tmp/temp-max-suffix.txt
          curl -fsSL "${max}" | awk '/DOMAIN-SUFFIX,/' | sed 's/DOMAIN-SUFFIX,//' >> ./tmp/temp-max-suffix.txt
          sort --ignore-case -u ./tmp/temp-max-suffix.txt > ./tmp/max-suffix.txt

          cat ./publish/hbo.txt | perl -ne '/^(full):([^:]+)(\n$|:\@.+)/ && print "DOMAIN,$2\n"' > ./tmp/temp-max-other.txt
          cat ./publish/hbo.txt | perl -ne '/^(keyword):([^:]+)(\n$|:\@.+)/ && print "DOMAIN-KEYWORD,$2\n"' >> ./tmp/temp-max-other.txt
          curl -fsSL "${max}" | awk '/(DOMAIN,|DOMAIN-KEYWORD,)/' >> ./tmp/temp-max-other.txt
          sort --ignore-case -u ./tmp/temp-max-other.txt > ./tmp/max-other.txt

      - name: Generate `primevideo`
        run: |
          cat ./publish/primevideo.txt | perl -ne '/^(domain):([^:]+)(\n$|:\@.+)/ && print "$2\n"' > ./tmp/temp-primevideo-suffix.txt
          curl -fsSL "${primevideo}" | awk '/DOMAIN-SUFFIX,/' | sed 's/DOMAIN-SUFFIX,//' >> ./tmp/temp-primevideo-suffix.txt
          sort --ignore-case -u ./tmp/temp-primevideo-suffix.txt > ./tmp/primevideo-suffix.txt

          cat ./publish/primevideo.txt | perl -ne '/^(full):([^:]+)(\n$|:\@.+)/ && print "DOMAIN,$2\n"' > ./tmp/temp-primevideo-other.txt
          cat ./publish/primevideo.txt | perl -ne '/^(keyword):([^:]+)(\n$|:\@.+)/ && print "DOMAIN-KEYWORD,$2\n"' >> ./tmp/temp-primevideo-other.txt
          curl -fsSL "${primevideo}" | awk '/(DOMAIN,|DOMAIN-KEYWORD,)/' >> ./tmp/temp-primevideo-other.txt
          sort --ignore-case -u ./tmp/temp-primevideo-other.txt > ./tmp/primevideo-other.txt

      - name: Generate `appletv`
        run: |
          cat ./publish/apple-tvplus.txt | perl -ne '/^(domain):([^:]+)(\n$|:\@.+)/ && print "$2\n"' > ./tmp/temp-appletv-suffix.txt
          curl -fsSL "${appletv}" | awk '/DOMAIN-SUFFIX,/' | sed 's/DOMAIN-SUFFIX,//' >> ./tmp/temp-appletv-suffix.txt
          sort --ignore-case -u ./tmp/temp-appletv-suffix.txt > ./tmp/appletv-suffix.txt

          cat ./publish/apple-tvplus.txt | perl -ne '/^(full):([^:]+)(\n$|:\@.+)/ && print "DOMAIN,$2\n"' > ./tmp/temp-appletv-other.txt
          cat ./publish/apple-tvplus.txt | perl -ne '/^(keyword):([^:]+)(\n$|:\@.+)/ && print "DOMAIN-KEYWORD,$2\n"' >> ./tmp/temp-appletv-other.txt
          curl -fsSL "${appletv}" | awk '/(DOMAIN,|DOMAIN-KEYWORD,)/' >> ./tmp/temp-appletv-other.txt
          sort --ignore-case -u ./tmp/temp-appletv-other.txt > ./tmp/appletv-other.txt

      - name: Generate `youtube`
        run: |
          cat ./publish/youtube.txt | perl -ne '/^(domain):([^:]+)(\n$|:\@.+)/ && print "$2\n"' > ./tmp/temp-youtube-suffix.txt
          curl -fsSL "${youtube}" | awk '/DOMAIN-SUFFIX,/' | sed 's/DOMAIN-SUFFIX,//' >> ./tmp/temp-youtube-suffix.txt
          sort --ignore-case -u ./tmp/temp-youtube-suffix.txt > ./tmp/youtube-suffix.txt

          cat ./publish/youtube.txt | perl -ne '/^(full):([^:]+)(\n$|:\@.+)/ && print "DOMAIN,$2\n"' > ./tmp/temp-youtube-other.txt
          cat ./publish/youtube.txt | perl -ne '/^(keyword):([^:]+)(\n$|:\@.+)/ && print "DOMAIN-KEYWORD,$2\n"' >> ./tmp/temp-youtube-other.txt
          curl -fsSL "${youtube}" | awk '/(DOMAIN,|DOMAIN-KEYWORD,)/' >> ./tmp/temp-youtube-other.txt
          sort --ignore-case -u ./tmp/temp-youtube-other.txt > ./tmp/youtube-other.txt

      - name: Generate `tiktok`
        run: |
          cat ./publish/tiktok.txt | perl -ne '/^(domain):([^:]+)(\n$|:\@.+)/ && print "$2\n"' > ./tmp/temp-tiktok-suffix.txt
          curl -fsSL "${tiktok}" | awk '/DOMAIN-SUFFIX,/' | sed 's/DOMAIN-SUFFIX,//' >> ./tmp/temp-tiktok-suffix.txt
          sort --ignore-case -u ./tmp/temp-tiktok-suffix.txt > ./tmp/tiktok-suffix.txt

          cat ./publish/tiktok.txt | perl -ne '/^(full):([^:]+)(\n$|:\@.+)/ && print "DOMAIN,$2\n"' > ./tmp/temp-tiktok-other.txt
          cat ./publish/tiktok.txt | perl -ne '/^(keyword):([^:]+)(\n$|:\@.+)/ && print "DOMAIN-KEYWORD,$2\n"' >> ./tmp/temp-tiktok-other.txt
          curl -fsSL "${tiktok}" | awk '/(DOMAIN,|DOMAIN-KEYWORD,)/' >> ./tmp/temp-tiktok-other.txt
          sort --ignore-case -u ./tmp/temp-tiktok-other.txt > ./tmp/tiktok-other.txt

      - name: Generate `bilibili`
        run: |
          cat ./publish/bilibili.txt | perl -ne '/^(domain):([^:]+)(\n$|:\@.+)/ && print "$2\n"' > ./tmp/temp-bilibili-suffix.txt
          curl -fsSL "${bilibili}" | awk '/DOMAIN-SUFFIX,/' | sed 's/DOMAIN-SUFFIX,//' >> ./tmp/temp-bilibili-suffix.txt
          sort --ignore-case -u ./tmp/temp-bilibili-suffix.txt > ./tmp/bilibili-suffix.txt

          cat ./publish/bilibili.txt | perl -ne '/^(full):([^:]+)(\n$|:\@.+)/ && print "DOMAIN,$2\n"' > ./tmp/temp-bilibili-other.txt
          cat ./publish/bilibili.txt | perl -ne '/^(keyword):([^:]+)(\n$|:\@.+)/ && print "DOMAIN-KEYWORD,$2\n"' >> ./tmp/temp-bilibili-other.txt
          curl -fsSL "${bilibili}" | awk '/(DOMAIN,|DOMAIN-KEYWORD,)/' >> ./tmp/temp-bilibili-other.txt
          sort --ignore-case -u ./tmp/temp-bilibili-other.txt > ./tmp/bilibili-other.txt

      - name: Generate `spotify`
        run: |
          cat ./publish/spotify.txt | perl -ne '/^(domain):([^:]+)(\n$|:\@.+)/ && print "$2\n"' > ./tmp/temp-spotify-suffix.txt
          curl -fsSL "${spotify}" | awk '/DOMAIN-SUFFIX,/' | sed 's/DOMAIN-SUFFIX,//' >> ./tmp/temp-spotify-suffix.txt
          sort --ignore-case -u ./tmp/temp-spotify-suffix.txt > ./tmp/spotify-suffix.txt

          cat ./publish/spotify.txt | perl -ne '/^(full):([^:]+)(\n$|:\@.+)/ && print "DOMAIN,$2\n"' > ./tmp/temp-spotify-other.txt
          cat ./publish/spotify.txt | perl -ne '/^(keyword):([^:]+)(\n$|:\@.+)/ && print "DOMAIN-KEYWORD,$2\n"' >> ./tmp/temp-spotify-other.txt
          curl -fsSL "${spotify}" | awk '/(DOMAIN,|DOMAIN-KEYWORD,)/' >> ./tmp/temp-spotify-other.txt
          sort --ignore-case -u ./tmp/temp-spotify-other.txt > ./tmp/spotify-other.txt

      - name: Generate `ai`
        run: |
          cp -f ./tmp/temp-ai-sort-suffix.txt ./tmp/ai-suffix.txt

          cat ./tmp/temp-ai-sort-domain.txt | sed 's/^/DOMAIN,/' > ./tmp/temp-ai-other.txt
          cat ./tmp/temp-ai-sort-keyword.txt | sed 's/^/DOMAIN-KEYWORD,/' >> ./tmp/temp-ai-other.txt
          cat ./tmp/temp-ai-other.txt | sort --ignore-case > ./tmp/ai-other.txt

      - name: Generate `media`
        run: |
          # Remove `ai` from `media` (suffix)
          python ./tools/removeFrom.py -remove ./tmp/temp-ai-sort-suffix.txt -from ./tmp/temp-media-sort-suffix.txt -out ./tmp/temp-media-without-ai-suffix.txt
          python ./tools/removeFrom.py -remove ./tmp/temp-ai-sort-domain.txt -from ./tmp/temp-media-without-ai-suffix.txt -out ./tmp/temp-media-without-ai-done-suffix.txt
          cat ./tmp/temp-media-without-ai-done-suffix.txt | sort --ignore-case > ./tmp/media-suffix.txt

          # Remove `ai` from `media` (domain)
          python ./tools/removeFrom.py -remove ./tmp/temp-ai-sort-suffix.txt -from ./tmp/temp-media-sort-domain.txt -out ./tmp/temp-media-without-ai-domain.txt
          python ./tools/removeFrom.py -remove ./tmp/temp-ai-sort-domain.txt -from ./tmp/temp-media-without-ai-domain.txt -out ./tmp/temp-media-without-ai-done-domain.txt
          cat ./tmp/temp-media-without-ai-done-domain.txt | sed 's/^/DOMAIN,/' | sort --ignore-case > ./tmp/temp-media-without-ai-filter-domain.txt
          cat ./tmp/temp-ai-sort-suffix.txt | sed 's/^/DOMAIN-SUFFIX,/' | sort --ignore-case > ./tmp/temp-ai-filter-suffix.txt
          cat ./tmp/temp-media-without-ai-filter-domain.txt ./tmp/temp-ai-filter-suffix.txt > ./tmp/temp-media-redundant.txt
          ./tools/filter.sh ./tmp/temp-media-redundant.txt > ./tmp/temp-media-done.txt
          cat ./tmp/temp-media-done.txt | awk '/DOMAIN,/' > ./tmp/temp-media-domain.txt

          # Remove `ai` from `media` (keyword)
          python ./tools/removeFrom.py -remove ./tmp/temp-ai-sort-keyword.txt -from ./tmp/temp-media-sort-keyword.txt -out ./tmp/temp-media-without-ai-done-keyword.txt
          cat ./tmp/temp-media-without-ai-done-keyword.txt | sed 's/^/DOMAIN-KEYWORD,/' | sort --ignore-case > ./tmp/temp-media-keyword.txt

          # Merge rules for `media`
          cat ./tmp/temp-media-domain.txt ./tmp/temp-media-keyword.txt > ./tmp/media-other.txt

      - name: Generate `networktest`
        run: |
          cat ./publish/test-ipv6.txt | perl -ne '/^(domain):([^:]+)(\n$|:\@!cn$)/ && print "$2\n"' > ./tmp/temp-networktest-suffix.txt
          cat ./publish/category-speedtest.txt | perl -ne '/^(domain):([^:]+)(\n$|:\@!cn$)/ && print "$2\n"' >> ./tmp/temp-networktest-suffix.txt
          cat ./publish/category-ip-geo-detect.txt | perl -ne '/^(domain):([^:]+)(\n$|:\@!cn$)/ && print "$2\n"' >> ./tmp/temp-networktest-suffix.txt
          curl -fsSL "${networktest}" | awk '/DOMAIN-SUFFIX,/' | sed 's/DOMAIN-SUFFIX,//' >> ./tmp/temp-networktest-suffix.txt
          sort --ignore-case -u ./tmp/temp-networktest-suffix.txt > ./tmp/networktest-suffix.txt

          cat ./publish/test-ipv6.txt | perl -ne '/^(full):([^:]+)(\n$|:\@!cn$)/ && print "DOMAIN,$2\n"' > ./tmp/temp-networktest-other.txt
          cat ./publish/test-ipv6.txt | perl -ne '/^(keyword):([^:]+)(\n$|:\@!cn$)/ && print "DOMAIN-KEYWORD,$2\n"' >> ./tmp/temp-networktest-other.txt
          cat ./publish/category-speedtest.txt | perl -ne '/^(full):([^:]+)(\n$|:\@!cn$)/ && print "DOMAIN,$2\n"' >> ./tmp/temp-networktest-other.txt
          cat ./publish/category-speedtest.txt | perl -ne '/^(keyword):([^:]+)(\n$|:\@!cn$)/ && print "DOMAIN-KEYWORD,$2\n"' >> ./tmp/temp-networktest-other.txt
          cat ./publish/category-ip-geo-detect.txt | perl -ne '/^(full):([^:]+)(\n$|:\@!cn$)/ && print "DOMAIN,$2\n"' >> ./tmp/temp-networktest-other.txt
          cat ./publish/category-ip-geo-detect.txt | perl -ne '/^(keyword):([^:]+)(\n$|:\@!cn$)/ && print "DOMAIN-KEYWORD,$2\n"' >> ./tmp/temp-networktest-other.txt
          curl -fsSL "${networktest}" | awk '/(DOMAIN,|DOMAIN-KEYWORD,)/' >> ./tmp/temp-networktest-other.txt
          sort --ignore-case -u ./tmp/temp-networktest-other.txt > ./tmp/networktest-other.txt

      - name: Generate `tld-proxy`
        run: |
          cat ./publish/tld-\!cn.txt | perl -ne '/^(domain):([^:]+)(\n$|:\@.+)/ && print "$2\n"' | sort --ignore-case > ./tmp/tld-proxy-suffix.txt

          cat ./publish/tld-\!cn.txt | perl -ne '/^(full):([^:]+)(\n$|:\@.+)/ && print "DOMAIN,$2\n"' > ./tmp/temp-tld-proxy-other.txt
          cat ./publish/tld-\!cn.txt | perl -ne '/^(keyword):([^:]+)(\n$|:\@.+)/ && print "DOMAIN-KEYWORD,$2\n"' >> ./tmp/temp-tld-proxy-other.txt
          sort --ignore-case ./tmp/temp-tld-proxy-other.txt > ./tmp/tld-proxy-other.txt

      - name: Generate `gfw`
        run: |
          cat ./tmp/temp-gfw.txt | perl -ne '/^((?=^.{3,255})[a-zA-Z0-9][-_a-zA-Z0-9]{0,62}(\.[a-zA-Z0-9][-_a-zA-Z0-9]{0,62})+)/ && print "$1\n"' | sed 's/^/DOMAIN-SUFFIX,/' | sort --ignore-case > ./domains/gfw.list

      - name: Generate `proxy`
        run: |
          cp -f ./tmp/temp-proxy-sort-suffix.txt ./tmp/proxy-suffix.txt

          cat ./tmp/temp-proxy-sort-domain.txt | sed 's/^/DOMAIN,/' > ./tmp/temp-proxy-other.txt
          cat ./tmp/temp-proxy-sort-keyword.txt | sed 's/^/DOMAIN-KEYWORD,/' >> ./tmp/temp-proxy-other.txt
          cat ./tmp/temp-proxy-other.txt | sort --ignore-case > ./tmp/proxy-other.txt

      - name: Generate `cn`
        run: |
          # Remove `proxy` from `cn` (suffix)
          python ./tools/removeFrom.py -remove ./tmp/temp-proxy-sort-suffix.txt -from ./tmp/temp-cn-sort-suffix.txt -out ./tmp/temp-cn-without-proxy-suffix.txt
          python ./tools/removeFrom.py -remove ./tmp/temp-proxy-sort-domain.txt -from ./tmp/temp-cn-without-proxy-suffix.txt -out ./tmp/temp-cn-without-proxy-done-suffix.txt
          cat ./tmp/temp-cn-without-proxy-done-suffix.txt | sort --ignore-case > ./tmp/cn-suffix.txt

          # Remove `proxy` from `cn` (domain)
          python ./tools/removeFrom.py -remove ./tmp/temp-proxy-sort-suffix.txt -from ./tmp/temp-cn-sort-domain.txt -out ./tmp/temp-cn-without-proxy-domain.txt
          python ./tools/removeFrom.py -remove ./tmp/temp-proxy-sort-domain.txt -from ./tmp/temp-cn-without-proxy-domain.txt -out ./tmp/temp-cn-without-proxy-done-domain.txt
          cat ./tmp/temp-cn-without-proxy-done-domain.txt | sed 's/^/DOMAIN,/' | sort --ignore-case > ./tmp/temp-cn-without-proxy-filter-domain.txt
          cat ./tmp/temp-cn-sort-suffix.txt | sed 's/^/DOMAIN-SUFFIX,/' | sort --ignore-case > ./tmp/temp-cn-filter-suffix.txt
          cat ./tmp/temp-cn-without-proxy-filter-domain.txt ./tmp/temp-cn-filter-suffix.txt > ./tmp/temp-cn-redundant.txt
          ./tools/filter.sh ./tmp/temp-cn-redundant.txt > ./tmp/temp-cn-done.txt
          cat ./tmp/temp-cn-done.txt | awk '/DOMAIN,/' > ./tmp/temp-cn-domain.txt

          # Remove `proxy` from `cn` (keyword)
          python ./tools/removeFrom.py -remove ./tmp/temp-proxy-sort-keyword.txt -from ./tmp/temp-cn-sort-keyword.txt -out ./tmp/temp-cn-without-proxy-done-keyword.txt
          cat ./tmp/temp-cn-without-proxy-done-keyword.txt | sed 's/^/DOMAIN-KEYWORD,/' | sort --ignore-case > ./tmp/temp-cn-keyword.txt

          # Merge rules for `cn`
          cat ./tmp/temp-cn-domain.txt ./tmp/temp-cn-keyword.txt > ./tmp/cn-other.txt

      - name: Generate `cn-lite`
        run: |
          # Remove `proxy` from `cn-lite` (suffix)
          python ./tools/removeFrom.py -remove ./tmp/temp-proxy-sort-suffix.txt -from ./tmp/temp-cn-lite-sort-suffix.txt -out ./tmp/temp-cn-lite-without-proxy-suffix.txt
          python ./tools/removeFrom.py -remove ./tmp/temp-proxy-sort-domain.txt -from ./tmp/temp-cn-lite-without-proxy-suffix.txt -out ./tmp/temp-cn-lite-without-proxy-done-suffix.txt
          cat ./tmp/temp-cn-lite-without-proxy-done-suffix.txt | sort --ignore-case > ./tmp/cn-lite-suffix.txt

          # Remove `proxy` from `cn-lite` (domain)
          python ./tools/removeFrom.py -remove ./tmp/temp-proxy-sort-suffix.txt -from ./tmp/temp-cn-lite-sort-domain.txt -out ./tmp/temp-cn-lite-without-proxy-domain.txt
          python ./tools/removeFrom.py -remove ./tmp/temp-proxy-sort-domain.txt -from ./tmp/temp-cn-lite-without-proxy-domain.txt -out ./tmp/temp-cn-lite-without-proxy-done-domain.txt
          cat ./tmp/temp-cn-lite-without-proxy-done-domain.txt | sed 's/^/DOMAIN,/' | sort --ignore-case > ./tmp/temp-cn-lite-without-proxy-filter-domain.txt
          cat ./tmp/temp-cn-lite-sort-suffix.txt | sed 's/^/DOMAIN-SUFFIX,/' | sort --ignore-case > ./tmp/temp-cn-lite-filter-suffix.txt
          cat ./tmp/temp-cn-lite-without-proxy-filter-domain.txt ./tmp/temp-cn-lite-filter-suffix.txt > ./tmp/temp-cn-lite-redundant.txt
          ./tools/filter.sh ./tmp/temp-cn-lite-redundant.txt > ./tmp/temp-cn-lite-done.txt
          cat ./tmp/temp-cn-lite-done.txt | awk '/DOMAIN,/' > ./tmp/temp-cn-lite-domain.txt

          # Remove `proxy` from `cn-lite` (keyword)
          python ./tools/removeFrom.py -remove ./tmp/temp-proxy-sort-keyword.txt -from ./tmp/temp-cn-lite-sort-keyword.txt -out ./tmp/temp-cn-lite-without-proxy-done-keyword.txt
          cat ./tmp/temp-cn-lite-without-proxy-done-keyword.txt | sed 's/^/DOMAIN-KEYWORD,/' | sort --ignore-case > ./tmp/temp-cn-lite-keyword.txt

          # Merge rules for `cn-lite`
          cat ./tmp/temp-cn-lite-domain.txt ./tmp/temp-cn-lite-keyword.txt > ./tmp/cn-lite-other.txt

      - name: Remove redundant domains
        run: |
          archs=(fakeip-filter fakeip-filter-lite private microsoft-cn apple-cn google-cn games-cn games netflix disney max primevideo appletv youtube tiktok bilibili spotify media ai networktest tld-proxy proxy cn cn-lite)
          for arch in "${archs[@]}"; do
            python ./tools/findRedundantDomain.py "./tmp/${arch}-suffix.txt" "./tmp/${arch}-deleted-unsort-suffix.txt"
            [ ! -f "./tmp/${arch}-deleted-unsort-suffix.txt" ] && touch "./tmp/${arch}-deleted-unsort-suffix.txt"
            sort --ignore-case "./tmp/${arch}-deleted-unsort-suffix.txt" > "./tmp/${arch}-deleted-sort-suffix.txt"

            python ./tools/removeFrom.py -remove "./tmp/${arch}-deleted-sort-suffix.txt" -from "./tmp/${arch}-suffix.txt" -out "./tmp/${arch}-none-redundant-suffix.txt"
            cat "./tmp/${arch}-none-redundant-suffix.txt" | sed 's/^/DOMAIN-SUFFIX,/' > "./tmp/${arch}-done-suffix.txt"
            cat "./tmp/${arch}-other.txt" "./tmp/${arch}-done-suffix.txt" | sort --ignore-case -u > "./tmp/${arch}-redundant.txt"

            ./tools/filter.sh "./tmp/${arch}-redundant.txt" > "./domains/${arch}.list"
          done

          rm -rf ./tmp* ./publish*

      - name: Release and upload `domains` assets
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          release_name: domains
          tag: domains
          overwrite: true
          body: |
            供下游项目 [DustinWin/ruleset_geodata](https://github.com/DustinWin/ruleset_geodata) 使用的 DOMAIN 数据源文件
            文件更新于 ${{ env.update_version }}
          file_glob: true
          file: ./domains/*

      - name: Git push assets to `domains` branch
        run: |
          cd ./domains/ || exit 1
          git init
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b domains
          git add . && git commit -m "DOMAIN 数据源文件更新于 ${update_version}"
          git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -f origin domains

      - name: Purge jsDelivr CDN
        run: |
          cd ./domains/ || exit 1
          for file in $(ls); do
            curl -i "https://purge.jsdelivr.net/gh/${{ github.repository }}@domains/${file}"
          done

      - name: Delete old workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 3
          keep_minimum_runs: 1
